# Generated by Django 3.1.5 on 2021-02-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='organisation',
            new_name='organization',
        ),
    ]
